server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

# Database settings.
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/pms  #Database pms
  validationQuery: "/* MyService Health Check */ SELECT 1"

#swagger:
#  resourcePackage: <a comma separated string of the packages that contain your @Api annotated resources>